language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
#  - "pypy"

install:
  - pip install -r requirements.txt --use-mirrors

before_script:
  - sh bin/travis-init.sh
  
services:
  - redis-server

script: ./run_tests

notifications:
  email:
    recipients: me@salimane.com
    on_success: change
    on_failure: always
