language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
#  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: ./run_tests
notifications:
  email:
    recipients: me@salimane.com
    on_success: change
    on_failure: always
